# Generated by Django 5.2.6 on 2025-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('mentor', 'Ментор'), ('organizer', 'Организатор'), ('admin', 'Админ')], max_length=20, verbose_name='Роль'),
        ),
    ]
