# Generated by Django 5.2.6 on 2025-11-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_enrollment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('mentor', 'Ментор')], max_length=20, verbose_name='Роль'),
        ),
    ]
