# Generated by Django 5.2.6 on 2025-11-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_subgroup'),
        ('learning', '0004_alter_enrollment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='groups.subgroup'),
        ),
    ]
