# Generated by Django 5.2.6 on 2025-11-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_enrollment_subgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='group',
        ),
    ]
