# Generated by Django 5.2.6 on 2025-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_enrollment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='role',
            field=models.CharField(choices=[('student', 'Студент')], max_length=20, verbose_name='Роль'),
        ),
    ]
