# Generated by Django 5.2.6 on 2025-11-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_progress', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.enrollment')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.learningstage')),
            ],
        ),
    ]
