# Generated by Django 5.2.6 on 2025-11-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_authuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
