# Generated by Django 5.2.6 on 2025-11-09 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_authuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='tab_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^\\w+$', 'Tab number must be words/digits/underscore')]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
