# Generated by Django 5.2.6 on 2025-11-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authuser_is_auth_alter_authuser_tab_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_role',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('organizer', 'Организатор')], max_length=20, null=True),
        ),
    ]
